"""init

Revision ID: 281124656923
Revises: 
Create Date: 2025-12-04 22:15:48.610292

"""


# revision identifiers, used by Alembic.
revision = '281124656923'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
