"""Add GoldSource statistics

Revision ID: 3cbb64e1a9de
Revises: dc3aa69c4a86
Create Date: 2026-01-31 20:59:14.504169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbb64e1a9de'
down_revision = 'dc3aa69c4a86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goldsource_maps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('map_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_name')
    )
    op.create_table('goldsource_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('steam_id', sa.String(length=32), nullable=False),
    sa.Column('registered', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goldsource_users_name'), 'goldsource_users', ['name'], unique=False)
    op.create_index(op.f('ix_goldsource_users_steam_id'), 'goldsource_users', ['steam_id'], unique=True)
    op.create_table('goldsource_servers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_server_id', sa.UUID(), nullable=False),
    sa.Column('server_uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_server_id'], ['game_servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goldsource_servers_game_server_id'), 'goldsource_servers', ['game_server_id'], unique=True)
    op.create_index(op.f('ix_goldsource_servers_server_uuid'), 'goldsource_servers', ['server_uuid'], unique=True)
    op.create_table('goldsource_fps',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.BigInteger(), nullable=False),
    sa.Column('fps', sa.Double(), nullable=True),
    sa.Column('players_online', sa.Integer(), nullable=True),
    sa.Column('map_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['goldsource_maps.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['goldsource_servers.id'], ),
    sa.PrimaryKeyConstraint('server_id', 'date')
    )
    op.create_index(op.f('ix_goldsource_fps_date'), 'goldsource_fps', ['date'], unique=False)
    op.create_table('goldsource_map_times',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('time_played', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['goldsource_maps.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['goldsource_servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['goldsource_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goldsource_map_times_map_id'), 'goldsource_map_times', ['map_id'], unique=False)
    op.create_index(op.f('ix_goldsource_map_times_server_id'), 'goldsource_map_times', ['server_id'], unique=False)
    op.create_index(op.f('ix_goldsource_map_times_user_id'), 'goldsource_map_times', ['user_id'], unique=False)
    op.create_table('goldsource_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=True),
    sa.Column('session_start', sa.BigInteger(), nullable=False),
    sa.Column('session_end', sa.BigInteger(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('headshots', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['goldsource_maps.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['goldsource_servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['goldsource_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goldsource_sessions_server_id'), 'goldsource_sessions', ['server_id'], unique=False)
    op.create_index(op.f('ix_goldsource_sessions_user_id'), 'goldsource_sessions', ['user_id'], unique=False)
    op.create_table('goldsource_user_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.BigInteger(), nullable=False),
    sa.Column('last_seen', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['goldsource_servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['goldsource_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goldsource_user_info_server_id'), 'goldsource_user_info', ['server_id'], unique=False)
    op.create_index(op.f('ix_goldsource_user_info_user_id'), 'goldsource_user_info', ['user_id'], unique=False)
    op.create_table('goldsource_kills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('killer_id', sa.Integer(), nullable=True),
    sa.Column('victim_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('weapon', sa.String(length=32), nullable=True),
    sa.Column('headshot', sa.Boolean(), nullable=False),
    sa.Column('date', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['killer_id'], ['goldsource_users.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['goldsource_servers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['goldsource_sessions.id'], ),
    sa.ForeignKeyConstraint(['victim_id'], ['goldsource_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goldsource_kills_date'), 'goldsource_kills', ['date'], unique=False)
    op.create_index(op.f('ix_goldsource_kills_killer_id'), 'goldsource_kills', ['killer_id'], unique=False)
    op.create_index(op.f('ix_goldsource_kills_server_id'), 'goldsource_kills', ['server_id'], unique=False)
    op.create_index(op.f('ix_goldsource_kills_victim_id'), 'goldsource_kills', ['victim_id'], unique=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goldsource_maps')
    op.drop_index(op.f('ix_goldsource_kills_victim_id'), table_name='goldsource_kills')
    op.drop_index(op.f('ix_goldsource_kills_server_id'), table_name='goldsource_kills')
    op.drop_index(op.f('ix_goldsource_kills_killer_id'), table_name='goldsource_kills')
    op.drop_index(op.f('ix_goldsource_kills_date'), table_name='goldsource_kills')
    op.drop_table('goldsource_kills')
    op.drop_index(op.f('ix_goldsource_user_info_user_id'), table_name='goldsource_user_info')
    op.drop_index(op.f('ix_goldsource_user_info_server_id'), table_name='goldsource_user_info')
    op.drop_table('goldsource_user_info')
    op.drop_index(op.f('ix_goldsource_sessions_user_id'), table_name='goldsource_sessions')
    op.drop_index(op.f('ix_goldsource_sessions_server_id'), table_name='goldsource_sessions')
    op.drop_table('goldsource_sessions')
    op.drop_index(op.f('ix_goldsource_map_times_user_id'), table_name='goldsource_map_times')
    op.drop_index(op.f('ix_goldsource_map_times_server_id'), table_name='goldsource_map_times')
    op.drop_index(op.f('ix_goldsource_map_times_map_id'), table_name='goldsource_map_times')
    op.drop_table('goldsource_map_times')
    op.drop_index(op.f('ix_goldsource_fps_date'), table_name='goldsource_fps')
    op.drop_table('goldsource_fps')
    op.drop_index(op.f('ix_goldsource_servers_server_uuid'), table_name='goldsource_servers')
    op.drop_index(op.f('ix_goldsource_servers_game_server_id'), table_name='goldsource_servers')
    op.drop_table('goldsource_servers')
    op.drop_index(op.f('ix_goldsource_users_steam_id'), table_name='goldsource_users')
    op.drop_index(op.f('ix_goldsource_users_name'), table_name='goldsource_users')
    op.drop_table('goldsource_users')
    op.drop_table('goldsource_maps')
    # ### end Alembic commands ###
