"""add_shop_system

Revision ID: 636cafa79446
Revises: 33ef3cb7f6b7
Create Date: 2026-02-08 13:03:30.177295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636cafa79446'
down_revision = '33ef3cb7f6b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_categories_slug'), 'shop_categories', ['slug'], unique=True)
    op.create_table('shop_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['shop_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_item_game_servers',
    sa.Column('shop_item_id', sa.UUID(), nullable=False),
    sa.Column('game_server_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['game_server_id'], ['game_servers.id'], ),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_items.id'], ),
    sa.PrimaryKeyConstraint('shop_item_id', 'game_server_id')
    )
    op.create_table('shop_item_game_types',
    sa.Column('shop_item_id', sa.UUID(), nullable=False),
    sa.Column('game_type_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['game_type_id'], ['game_types.id'], ),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_items.id'], ),
    sa.PrimaryKeyConstraint('shop_item_id', 'game_type_id')
    )
    op.create_table('shop_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('game_server_id', sa.UUID(), nullable=False),
    sa.Column('price_paid', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_server_id'], ['game_servers.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['shop_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_orders_status'), 'shop_orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_orders_status'), table_name='shop_orders')
    op.drop_table('shop_orders')
    op.drop_table('shop_item_game_types')
    op.drop_table('shop_item_game_servers')
    op.drop_table('shop_items')
    op.drop_index(op.f('ix_shop_categories_slug'), table_name='shop_categories')
    op.drop_table('shop_categories')
    # ### end Alembic commands ###
