"""add_shop_item_platform_requirement

Revision ID: ef110abe7d2d
Revises: 636cafa79446
Create Date: 2026-02-08 14:06:16.954508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef110abe7d2d'
down_revision = '636cafa79446'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_items', sa.Column('required_platform', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_items', 'required_platform')
    # ### end Alembic commands ###
